import type { Metadata } from "next";
import '../../globals.css';

import { Manrope } from 'next/font/google';

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <div className="flex w-full shrink-0 flex-col">
          <div> This is the header of your docs</div>
          {children}
          <div> This is the footer of your docs</div>
        </div>
      </body>
    </html>
  );
}
